<script src="{!! asset('public/js/jquery-1.10.2.min.js') !!}"></script>
<script src="{!! asset('public/js/jquery-migrate-1.2.1.min.js ') !!}"></script>
<script src="{!! asset('public/js/jquery-ui.js ') !!}"></script><!--loading bootstrap js-->
<script src="{!! asset('public/vendors/bootstrap/js/bootstrap.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js ') !!}"></script>
<script src="{!! asset('public/js/html5shiv.js ') !!}"></script>
<script src="{!! asset('public/js/respond.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/metisMenu/jquery.metisMenu.js ') !!}"></script>
<script src="{!! asset('public/vendors/slimScroll/jquery.slimscroll.js ') !!}"></script>
<script src="{!! asset('public/vendors/jquery-cookie/jquery.cookie.js ') !!}"></script>
<script src="{!! asset('public/vendors/iCheck/icheck.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/iCheck/custom.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/jquery-notific8/jquery.notific8.min.js ') !!}"></script>
<!--<script src="{!! asset('public/vendors/jquery-highcharts/highcharts.js ') !!}"></script>-->
<script src="{!! asset('public/js/jquery.menu.js ') !!}"></script>
<!--<script src="{!! asset('public/vendors/jquery-pace/pace.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/holder/holder.js ') !!}"></script>-->
<script src="{!! asset('public/vendors/responsive-tabs/responsive-tabs.js ') !!}"></script>
<script src="{!! asset('public/vendors/jquery-news-ticker/jquery.newsTicker.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/moment/moment.js ') !!}"></script>
<script src="{!! asset('public/vendors/bootstrap-datepicker/js/bootstrap-datepicker.js ') !!}"></script>
<script src="{!! asset('public/vendors/bootstrap-daterangepicker/daterangepicker.js ') !!}"></script><!--CORE JAVASCRIPT-->
<script src="{!! asset('public/js/main.js ') !!}"></script><!--LOADING SCRIPTS FOR PAGE-->
<!--<script src="{!! asset('public/vendors/intro.js/intro.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.categories.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.pie.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.tooltip.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.resize.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.fillbetween.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.stack.js ') !!}"></script>
<script src="{!! asset('public/vendors/flot-chart/jquery.flot.spline.js ') !!}"></script>-->
<script src="{!! asset('public/vendors/calendar/zabuto_calendar.min.js ') !!}"></script>
<script src="{!! asset('public/vendors/sco.message/sco.message.js ') !!}"></script>
<script src="{!! asset('public/vendors/intro.js/intro.js ') !!}"></script>
<!--<script src="{!! asset('public/js/index.js ') !!}"></script> -->
<script src="{!! asset('public/vendors/jquery-validate/jquery.validate.min.js') !!}"></script>
<script src="{!! asset('public/js/form-validation.js') !!}"></script>
<script src="{!! asset('public/js/functions.js') !!}"></script>